services:
  redis:
    image: 'redis:7.2.2'
    ports:
      - '6379'
    volumes:
      - 'data:/var/lib/redis/data'

  app:
    build: .
    env_file: .env
    environment: &app_env
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - '.:/forecast'
    ports:
      - '3000:3000'
    depends_on:
      - redis

volumes:
  data: {}
