version: '3.0'

services:
  redis:
    image: 'redis:7.2.2'
    ports:
      - '6379'
    volumes:
      - 'data:/var/lib/redis/data'

  app:
    build: .
    command: bash -c "bundle install; ./bin/web start_dev"
    tty: true
    stdin_open: true
    env_file: .env
    environment: &app_env
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - '.:/forecast'
      - bundle_path:/usr/local/bundle/
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    links:
      - redis

volumes:
  data: {}
  bundle_path:
  node_modules:
